version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/usr/src/app/logs
      - ./downloads:/usr/src/app/downloads
    restart: unless-stopped 